### ISSUE TITLE
how...

### ISSUE THREAD

**Issue by ghost** [jpt13653903/EngCalc#1]
how the hell isn't this more popular? by far one of the most useful tools i've come accross in here.

**Comment by jpt13653903** [comment]
Thank you for the complement :-)

**Comment by ghost** [comment]
> Thank you for the complement :-)

no need to thank me, if anything it's me that should be thanking you because this is an extremely useful tool, I hope more people see this. oh and please create a release with 1.9 here on github

**Comment by jpt13653903** [comment]
Done.

You can also download the latest [from SourceForge](https://sourceforge.net/projects/alwaysontopcalc/files/latest/download), of course, but I do see the convenience of having the releases on GitHub directly.

**Comment by ghost** [comment]
yeah I've downloaded it from there but github is a much better site so it's nice to have it here
